version: "2"
services:
    test_trial:
        build: ./
        entrypoint: 
            - python
            - /brapi_to_isa.py
            - -e
            - https://urgi.versailles.inra.fr/gnpis-core-srv/brapi/v1/
            - -t
            - "24"
        volumes:
         - ./outputdir:/outputdir
    test_study:
        build: ./
        entrypoint: 
            - python
            - /brapi_to_isa.py
            - -e
            - https://urgi.versailles.inra.fr/gnpis-core-srv/brapi/v1/
            - -s
            - "RIGW1"
        volumes:
         - ./outputdir:/outputdir
    test_studies_notrial:
        build: ./
        entrypoint: 
            - python
            - /brapi_to_isa.py
            - -e
            - https://urgi.versailles.inra.fr/gnpis-core-srv/brapi/v1/
            - -s
            - RIGW1,GWAS_Tomato_Solcap_Avignon
        volumes:
         - ./outputdir:/outputdir
    test_pippa:
        build: ./
        entrypoint: 
            - python
            - /brapi_to_isa.py
            - -e
            - https://pippa.psb.ugent.be/BrAPIPPA/brapi/v1/
            - -s
            - "VIB_study___55"
        volumes:
         - ./outputdir:/outputdir
    BrAPI2ISA:
        build: ./
        entrypoint: 
            - python
            - /brapi_to_isa.py
        volumes:
         - ./outputdir:/outputdir
